### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

[[overview]]
title = "Overview"
identifier = "overview"

[[install]]
title = "Install"
identifier = "install"

[[features]]
title = "Features"
identifier = "features"

  [[features]]
  title = "Agentless"
  identifier = "features/agentless"
  parent = "features"

  [[features]]
  title = "Chef Solo"
  identifier = "features/chef_solo"
  parent = "features"

  [[features]]
  title = "Ohai"
  identifier = "features/ohai"
  parent = "features"

[[integrations]]
title = "Integrations"
identifier = "integrations"

  [[integrations]]
  title = "Azure"
  identifier = "integrations/azure"
  parent = "integrations"

  [[integrations]]
  title = "Windows"
  identifier = "integrations/windows"
  parent = "integrations"

[[policy]]
title = "Policy"
identifier = "policy"

[[security]]
title = "Security"
identifier = "security"

[[cookbooks]]
title = "Cookbooks"
identifier = "cookbooks"

  [[cookbooks]]
  title = "Attributes"
  identifier = "cookbooks/attributes"
  parent = "cookbooks"
  weight = 30

  [[cookbooks]]
  title = "Recipes"
  identifier = "cookbooks/recipes"
  parent = "cookbooks"
  weight = 70

[[infra_language]]
title = "Infra language"
identifier = "infra_language"

[[resources]]
title = "Resources"
identifier = "resources"

  [[resources]]
  title = "Bundled resources"
  parent = "resources"
  identifier = "resources/bundled"

  [[resources]]
  title = "Custom resources"
  parent = "resources"
  identifier = "resources/custom"

[[extension_apis]]
title = "Extension APIs"
identifier = "extension_apis"

  [[extension_apis]]
  title = "Compliance DSL"
  identifier = "extension_apis/inspec/dsl_inspec/ Compliance DSL"
  parent = "extension_apis"
  url = "https://docs.chef.io/inspec/latest/profiles/controls/"
  weight = 20

  [[extension_apis]]
  title = "Handlers"
  identifier = "extension_apis/handlers"
  parent = "extension_apis"
  weight = 20

    [[extension_apis]]
    title = "Custom handlers"
    identifier = "extension_apis/handlers/handlers.md#custom-handlers Custom Handlers"
    parent = "extension_apis/handlers"
    url = "/features/handlers/#custom-handlers"
    weight = 10

    [[extension_apis]]
    title = "Community handlers"
    identifier = "extension_apis/handlers/plugin_community.md#handlers Community Handlers"
    parent = "extension_apis/handlers"
    url = "/extension_apis/community_plugins/#handlers"
    weight = 30

  [[extension_apis]]
  title = "Ohai plugins"
  identifier = "extension_apis/ohai_plugins"
  parent = "extension_apis"
  weight = 40

[[reference]]
title = "Reference"
identifier = "reference"

    [[reference]]
    title = "chef-solo (executable)"
    identifier = "reference/ctl_chef_solo.md chef-solo (executable)"
    parent = "reference"
    url = "/features/chef_solo/ctl_chef_solo/"
    weight = 20

    [[reference]]
    title = "Handler DSL"
    identifier = "reference/dsl_handler.md Handler Commands"
    parent = "reference"
    url = "/extension_apis/dsl_handler/"
    weight = 40

    [[reference]]
    title = "ohai (executable)"
    identifier = "reference/ctl_ohai.md ohai (executable)"
    parent = "reference"
    url = "/features/ohai/ctl_ohai/"
    weight = 50

    [[reference]]
    title = "supermarket-ctl"
    identifier = "supermarket/reference/ctl_supermarket.md supermarket-ctl"
    parent = "reference"
    url = "https://docs.chef.io/supermarket/ctl_supermarket/"
    weight = 60

    [[reference]]
    title = "client.rb"
    identifier = "reference/config_rb_client.md client.rb"
    parent = "reference"
    url = "/install/config_rb_client/"
    weight = 70

    [[reference]]
    title = "metadata.rb"
    identifier = "reference/config_rb_metadata.md metadata.rb"
    parent = "reference"
    url = "/cookbooks/config_rb_metadata/"
    weight = 80

    [[reference]]
    title = "Policyfile.rb"
    identifier = "reference/config_rb_policyfile.md Policyfile.rb"
    parent = "reference"
    url = "/policy/config_rb_policyfile/"
    weight = 90

    [[reference]]
    title = "solo.rb"
    identifier = "reference/config_rb_solo.md solo.rb"
    parent = "reference"
    url = "/install/config_rb_solo/"
    weight = 100